[package]
name = "rust-dm"
version = "0.1.0"
authors = ["Camille TJHOA <camille@contract-live.com>"]

[dependencies]
error-chain = "0.9"
log = "0.3.6"
reqwest = "0.4"
rocket = "0.2"
rocket_codegen = "0.2"
semver = "0.6"
toml = "0.3"
