[package]
name = "rust-dm"
version = "0.1.0"
authors = ["Camille TJHOA <camille@contract-live.com>"]

[dependencies]
reqwest = "0.2.0"
rocket = "0.1.4"
rocket_codegen = "0.1.4"
toml = "0.2"
semver = "0.5.1"
