[package]
name = "rust-dm"
version = "0.1.0"
authors = ["Camille TJHOA <camille@contract-live.com>"]

[dependencies]
reqwest = "0.4.0"
rocket = "0.2.0"
rocket_codegen = "0.2.0"
semver = "0.6"
toml = "0.3"
